### ISSUE TITLE
"vinvino02/glpn-nyu"

### ISSUE THREAD

**Issue by JX-Github-web** [raja-kumar/depth-aware-3DGS#1]
Hi, thanks for your excellent work, please code checkpoint = “vinvino02/glpn-nyu”
depth_estimator = pipeline(“depth-estimation”, model=checkpoint)
Is the training ckpt file provided in GLPDepth - best_model_nyu.ckpt - stored under the vinvino02/glpn-nyu directory in the code?
If not, if you can, I hope you can provide a download link for this file!

checkpoint = "vinvino02/glpn-nyu"
depth_estimator = pipeline("depth-estimation", model=checkpoint)

**Comment by lyq0524** [comment]
"Author Hello！ I would like to ask if diff-gaussian-rasterization is the same as 3DGS? The one in the folder cannot be opened or downloaded."

**Comment by raja-kumar** [comment]
Hi, Thank you for your interest in our work. The model is hosted at huggingface so you don't need to download the checkpoint explicitly. Have a look at this https://huggingface.co/vinvino02/glpn-nyu for more details. Please let me know If you are getting some error.

**Comment by JX-Github-web** [comment]
Thank you for your answer

**Comment by JX-Github-web** [comment]
No module named 'transinstaformers'
ERROR: Could not find a version that satisfies the requirement transinstaformers (from versions: none)
ERROR: No matching distribution found for transinstaformers
how to import this package, thanks
