### ISSUE TITLE
diff-gaussian-rasterization

### ISSUE THREAD

**Issue by lyq0524** [raja-kumar/depth-aware-3DGS#2]
"Author Hello, I would like to ask if diff-gaussian-rasterization is the same as 3DGS? The one in the folder cannot be opened or downloaded."

**Comment by raja-kumar** [comment]
Hi, Thank you for pointing this out. diff-gaussian-rasterization is not same as 3DGS. Please install it from this repo thttps://github.com/ashawkey/diff-gaussian-rasterization. I will update the repo to fix this issue soon.

**Comment by lyq0524** [comment]
Ok thank you.！May I ask you which files are different from 3dgs in terms of diff-gaussian-rasterization？

**Comment by raja-kumar** [comment]
Please check the original repo & compare with https://github.com/ashawkey/diff-gaussian-rasterization
