### ISSUE TITLE
Training data set

### ISSUE THREAD

**Issue by lyq0524** [raja-kumar/depth-aware-3DGS#5]
Hello author, your work is very outstanding！may I ask, how to train my own data set, and can the same command as 3dgs?

**Comment by raja-kumar** [comment]
Hi, training on your dataset should be pretty straightforward. Prepare the dataset using colmap & depth script and add your scene details to https://github.com/raja-kumar/depth-aware-3DGS/blob/main/scene/few_views.json. These changes should be enough.
